/*     */ package org.apache.commons.math3.exception.util;
/*     */ 
/*     */ import java.util.Locale;
/*     */ import java.util.MissingResourceException;
/*     */ import java.util.ResourceBundle;
/*     */ 
/*     */ public enum LocalizedFormats implements Localizable {
/*  44 */   ARGUMENT_OUTSIDE_DOMAIN("Argument {0} outside domain [{1} ; {2}]"),
/*  45 */   ARRAY_SIZE_EXCEEDS_MAX_VARIABLES("array size cannot be greater than {0}"),
/*  46 */   ARRAY_SIZES_SHOULD_HAVE_DIFFERENCE_1("array sizes should have difference 1 ({0} != {1} + 1)"),
/*  47 */   ARRAY_SUMS_TO_ZERO("array sums to zero"),
/*  48 */   ASSYMETRIC_EIGEN_NOT_SUPPORTED("eigen decomposition of assymetric matrices not supported yet"),
/*  49 */   AT_LEAST_ONE_COLUMN("matrix must have at least one column"),
/*  50 */   AT_LEAST_ONE_ROW("matrix must have at least one row"),
/*  51 */   BANDWIDTH("bandwidth ({0})"),
/*  52 */   BINOMIAL_INVALID_PARAMETERS_ORDER("must have n >= k for binomial coefficient (n, k), got k = {0}, n = {1}"),
/*  53 */   BINOMIAL_NEGATIVE_PARAMETER("must have n >= 0 for binomial coefficient (n, k), got n = {0}"),
/*  54 */   CANNOT_CLEAR_STATISTIC_CONSTRUCTED_FROM_EXTERNAL_MOMENTS("statistics constructed from external moments cannot be cleared"),
/*  55 */   CANNOT_COMPUTE_0TH_ROOT_OF_UNITY("cannot compute 0-th root of unity, indefinite result"),
/*  56 */   CANNOT_COMPUTE_BETA_DENSITY_AT_0_FOR_SOME_ALPHA("cannot compute beta density at 0 when alpha = {0,number}"),
/*  57 */   CANNOT_COMPUTE_BETA_DENSITY_AT_1_FOR_SOME_BETA("cannot compute beta density at 1 when beta = %.3g"),
/*  58 */   CANNOT_COMPUTE_NTH_ROOT_FOR_NEGATIVE_N("cannot compute nth root for null or negative n: {0}"),
/*  59 */   CANNOT_DISCARD_NEGATIVE_NUMBER_OF_ELEMENTS("cannot discard a negative number of elements ({0})"),
/*  60 */   CANNOT_FORMAT_INSTANCE_AS_3D_VECTOR("cannot format a {0} instance as a 3D vector"),
/*  61 */   CANNOT_FORMAT_INSTANCE_AS_COMPLEX("cannot format a {0} instance as a complex number"),
/*  62 */   CANNOT_FORMAT_INSTANCE_AS_REAL_VECTOR("cannot format a {0} instance as a real vector"),
/*  63 */   CANNOT_FORMAT_OBJECT_TO_FRACTION("cannot format given object as a fraction number"),
/*  64 */   CANNOT_INCREMENT_STATISTIC_CONSTRUCTED_FROM_EXTERNAL_MOMENTS("statistics constructed from external moments cannot be incremented"),
/*  65 */   CANNOT_NORMALIZE_A_ZERO_NORM_VECTOR("cannot normalize a zero norm vector"),
/*  66 */   CANNOT_RETRIEVE_AT_NEGATIVE_INDEX("elements cannot be retrieved from a negative array index {0}"),
/*  67 */   CANNOT_SET_AT_NEGATIVE_INDEX("cannot set an element at a negative index {0}"),
/*  68 */   CANNOT_SUBSTITUTE_ELEMENT_FROM_EMPTY_ARRAY("cannot substitute an element from an empty array"),
/*  69 */   CANNOT_TRANSFORM_TO_DOUBLE("Conversion Exception in Transformation: {0}"),
/*  70 */   CARDAN_ANGLES_SINGULARITY("Cardan angles singularity"),
/*  71 */   CLASS_DOESNT_IMPLEMENT_COMPARABLE("class ({0}) does not implement Comparable"),
/*  72 */   CLOSEST_ORTHOGONAL_MATRIX_HAS_NEGATIVE_DETERMINANT("the closest orthogonal matrix has a negative determinant {0}"),
/*  73 */   COLUMN_INDEX_OUT_OF_RANGE("column index {0} out of allowed range [{1}, {2}]"),
/*  74 */   COLUMN_INDEX("column index ({0})"),
/*  75 */   CONTINUED_FRACTION_INFINITY_DIVERGENCE("Continued fraction convergents diverged to +/- infinity for value {0}"),
/*  76 */   CONTINUED_FRACTION_NAN_DIVERGENCE("Continued fraction diverged to NaN for value {0}"),
/*  77 */   CONTRACTION_CRITERIA_SMALLER_THAN_EXPANSION_FACTOR("contraction criteria ({0}) smaller than the expansion factor ({1}).  This would lead to a never ending loop of expansion and contraction as a newly expanded internal storage array would immediately satisfy the criteria for contraction."),
/*  78 */   CONTRACTION_CRITERIA_SMALLER_THAN_ONE("contraction criteria smaller than one ({0}).  This would lead to a never ending loop of expansion and contraction as an internal storage array length equal to the number of elements would satisfy the contraction criteria."),
/*  79 */   CONVERGENCE_FAILED("convergence failed"),
/*  80 */   CROSSING_BOUNDARY_LOOPS("some outline boundary loops cross each other"),
/*  81 */   CROSSOVER_RATE("crossover rate ({0})"),
/*  82 */   CUMULATIVE_PROBABILITY_RETURNED_NAN("Cumulative probability function returned NaN for argument {0} p = {1}"),
/*  83 */   DIFFERENT_ROWS_LENGTHS("some rows have length {0} while others have length {1}"),
/*  84 */   DIFFERENT_ORIG_AND_PERMUTED_DATA("original and permuted data must contain the same elements"),
/*  85 */   DIGEST_NOT_INITIALIZED("digest not initialized"),
/*  86 */   DIMENSIONS_MISMATCH_2x2("got {0}x{1} but expected {2}x{3}"),
/*  87 */   DIMENSIONS_MISMATCH_SIMPLE("{0} != {1}"),
/*  88 */   DIMENSIONS_MISMATCH("dimensions mismatch"),
/*  89 */   DISCRETE_CUMULATIVE_PROBABILITY_RETURNED_NAN("Discrete cumulative probability function returned NaN for argument {0}"),
/*  90 */   DISTRIBUTION_NOT_LOADED("distribution not loaded"),
/*  91 */   DUPLICATED_ABSCISSA("Abscissa {0} is duplicated at both indices {1} and {2}"),
/*  92 */   ELITISM_RATE("elitism rate ({0})"),
/*  93 */   EMPTY_CLUSTER_IN_K_MEANS("empty cluster in k-means"),
/*  94 */   EMPTY_POLYNOMIALS_COEFFICIENTS_ARRAY("empty polynomials coefficients array"),
/*  95 */   EMPTY_SELECTED_COLUMN_INDEX_ARRAY("empty selected column index array"),
/*  96 */   EMPTY_SELECTED_ROW_INDEX_ARRAY("empty selected row index array"),
/*  97 */   EMPTY_STRING_FOR_IMAGINARY_CHARACTER("empty string for imaginary character"),
/*  98 */   ENDPOINTS_NOT_AN_INTERVAL("endpoints do not specify an interval: [{0}, {1}]"),
/*  99 */   EQUAL_VERTICES_IN_SIMPLEX("equal vertices {0} and {1} in simplex configuration"),
/* 100 */   EULER_ANGLES_SINGULARITY("Euler angles singularity"),
/* 101 */   EVALUATION("evaluation"),
/* 102 */   EXPANSION_FACTOR_SMALLER_THAN_ONE("expansion factor smaller than one ({0})"),
/* 103 */   FACTORIAL_NEGATIVE_PARAMETER("must have n >= 0 for n!, got n = {0}"),
/* 104 */   FAILED_BRACKETING("number of iterations={4}, maximum iterations={5}, initial={6}, lower bound={7}, upper bound={8}, final a value={0}, final b value={1}, f(a)={2}, f(b)={3}"),
/* 105 */   FAILED_FRACTION_CONVERSION("Unable to convert {0} to fraction after {1} iterations"),
/* 106 */   FIRST_COLUMNS_NOT_INITIALIZED_YET("first {0} columns are not initialized yet"),
/* 107 */   FIRST_ELEMENT_NOT_ZERO("first element is not 0: {0}"),
/* 108 */   FIRST_ROWS_NOT_INITIALIZED_YET("first {0} rows are not initialized yet"),
/* 109 */   FRACTION_CONVERSION_OVERFLOW("Overflow trying to convert {0} to fraction ({1}/{2})"),
/* 110 */   FUNCTION_NOT_DIFFERENTIABLE("function is not differentiable"),
/* 111 */   FUNCTION_NOT_POLYNOMIAL("function is not polynomial"),
/* 112 */   GCD_OVERFLOW_32_BITS("overflow: gcd({0}, {1}) is 2^31"),
/* 113 */   GCD_OVERFLOW_64_BITS("overflow: gcd({0}, {1}) is 2^63"),
/* 114 */   HOLE_BETWEEN_MODELS_TIME_RANGES("{0} wide hole between models time ranges"),
/* 115 */   IDENTICAL_ABSCISSAS_DIVISION_BY_ZERO("identical abscissas x[{0}] == x[{1}] == {2} cause division by zero"),
/* 116 */   ILL_CONDITIONED_OPERATOR("condition number {1} is too high "),
/* 117 */   INDEX_LARGER_THAN_MAX("the index specified: {0} is larger than the current maximal index {1}"),
/* 118 */   INDEX_NOT_POSITIVE("index ({0}) is not positive"),
/* 119 */   INDEX_OUT_OF_RANGE("index {0} out of allowed range [{1}, {2}]"),
/* 120 */   INDEX("index ({0})"),
/* 121 */   NOT_FINITE_NUMBER("{0} is not a finite number"),
/* 122 */   INFINITE_BOUND("interval bounds must be finite"),
/* 123 */   ARRAY_ELEMENT("value {0} at index {1}"),
/* 124 */   INFINITE_ARRAY_ELEMENT("Array contains an infinite element, {0} at index {1}"),
/* 125 */   INFINITE_VALUE_CONVERSION("cannot convert infinite value"),
/* 126 */   INITIAL_CAPACITY_NOT_POSITIVE("initial capacity ({0}) is not positive"),
/* 127 */   INITIAL_COLUMN_AFTER_FINAL_COLUMN("initial column {1} after final column {0}"),
/* 128 */   INITIAL_ROW_AFTER_FINAL_ROW("initial row {1} after final row {0}"),
/* 129 */   INPUT_DATA_FROM_UNSUPPORTED_DATASOURCE("input data comes from unsupported datasource: {0}, supported sources: {1}, {2}"),
/* 130 */   INSTANCES_NOT_COMPARABLE_TO_EXISTING_VALUES("instance of class {0} not comparable to existing values"),
/* 131 */   INSUFFICIENT_DATA_FOR_T_STATISTIC("insufficient data for t statistic, needs at least 2, got {0}"),
/* 132 */   INSUFFICIENT_DIMENSION("insufficient dimension {0}, must be at least {1}"),
/* 133 */   DIMENSION("dimension ({0})"),
/* 134 */   INSUFFICIENT_OBSERVED_POINTS_IN_SAMPLE("sample contains {0} observed points, at least {1} are required"),
/* 135 */   INSUFFICIENT_ROWS_AND_COLUMNS("insufficient data: only {0} rows and {1} columns."),
/* 136 */   INTEGRATION_METHOD_NEEDS_AT_LEAST_TWO_PREVIOUS_POINTS("{0} method needs at least two previous points"),
/* 137 */   INTERNAL_ERROR("internal error, please fill a bug report at {0}"),
/* 138 */   INVALID_BINARY_DIGIT("invalid binary digit: {0}"),
/* 139 */   INVALID_BINARY_CHROMOSOME("binary mutation works on BinaryChromosome only"),
/* 140 */   INVALID_BRACKETING_PARAMETERS("invalid bracketing parameters:  lower bound={0},  initial={1}, upper bound={2}"),
/* 141 */   INVALID_FIXED_LENGTH_CHROMOSOME("one-point crossover only works with fixed-length chromosomes"),
/* 142 */   INVALID_INTERVAL_INITIAL_VALUE_PARAMETERS("invalid interval, initial value parameters:  lower={0}, initial={1}, upper={2}"),
/* 143 */   INVALID_ITERATIONS_LIMITS("invalid iteration limits: min={0}, max={1}"),
/* 144 */   INVALID_MAX_ITERATIONS("bad value for maximum iterations number: {0}"),
/* 145 */   NOT_ENOUGH_DATA_REGRESSION("the number of observations is not sufficient to conduct regression"),
/* 146 */   INVALID_REGRESSION_ARRAY("input data array length = {0} does not match the number of observations = {1} and the number of regressors = {2}"),
/* 147 */   INVALID_REGRESSION_OBSERVATION("length of regressor array = {0} does not match the number of variables = {1} in the model"),
/* 148 */   INVALID_ROUNDING_METHOD("invalid rounding method {0}, valid methods: {1} ({2}), {3} ({4}), {5} ({6}), {7} ({8}), {9} ({10}), {11} ({12}), {13} ({14}), {15} ({16})"),
/* 149 */   ITERATOR_EXHAUSTED("iterator exhausted"),
/* 150 */   LCM_OVERFLOW_32_BITS("overflow: lcm({0}, {1}) is 2^31"),
/* 151 */   LCM_OVERFLOW_64_BITS("overflow: lcm({0}, {1}) is 2^63"),
/* 152 */   LIST_OF_CHROMOSOMES_BIGGER_THAN_POPULATION_SIZE("list of chromosomes bigger than maxPopulationSize"),
/* 153 */   LOESS_EXPECTS_AT_LEAST_ONE_POINT("Loess expects at least 1 point"),
/* 154 */   LOWER_BOUND_NOT_BELOW_UPPER_BOUND("lower bound ({0}) must be strictly less than upper bound ({1})"),
/* 155 */   LOWER_ENDPOINT_ABOVE_UPPER_ENDPOINT("lower endpoint ({0}) must be less than or equal to upper endpoint ({1})"),
/* 156 */   MAP_MODIFIED_WHILE_ITERATING("map has been modified while iterating"),
/* 157 */   EVALUATIONS("evaluations"),
/* 158 */   MAX_COUNT_EXCEEDED("maximal count ({0}) exceeded"),
/* 159 */   MAX_ITERATIONS_EXCEEDED("maximal number of iterations ({0}) exceeded"),
/* 160 */   MINIMAL_STEPSIZE_REACHED_DURING_INTEGRATION("minimal step size ({1,number,0.00E00}) reached, integration needs {0,number,0.00E00}"),
/* 161 */   MISMATCHED_LOESS_ABSCISSA_ORDINATE_ARRAYS("Loess expects the abscissa and ordinate arrays to be of the same size, but got {0} abscissae and {1} ordinatae"),
/* 162 */   MUTATION_RATE("mutation rate ({0})"),
/* 163 */   NAN_ELEMENT_AT_INDEX("element {0} is NaN"),
/* 164 */   NAN_VALUE_CONVERSION("cannot convert NaN value"),
/* 165 */   NEGATIVE_BRIGHTNESS_EXPONENT("brightness exponent should be positive or null, but got {0}"),
/* 166 */   NEGATIVE_COMPLEX_MODULE("negative complex module {0}"),
/* 167 */   NEGATIVE_ELEMENT_AT_2D_INDEX("element ({0}, {1}) is negative: {2}"),
/* 168 */   NEGATIVE_ELEMENT_AT_INDEX("element {0} is negative: {1}"),
/* 169 */   NEGATIVE_NUMBER_OF_SUCCESSES("number of successes must be non-negative ({0})"),
/* 170 */   NUMBER_OF_SUCCESSES("number of successes ({0})"),
/* 171 */   NEGATIVE_NUMBER_OF_TRIALS("number of trials must be non-negative ({0})"),
/* 172 */   NUMBER_OF_INTERPOLATION_POINTS("number of interpolation points ({0})"),
/* 173 */   NUMBER_OF_TRIALS("number of trials ({0})"),
/* 174 */   ROBUSTNESS_ITERATIONS("number of robustness iterations ({0})"),
/* 175 */   START_POSITION("start position ({0})"),
/* 176 */   NON_CONVERGENT_CONTINUED_FRACTION("Continued fraction convergents failed to converge (in less than {0} iterations) for value {1}"),
/* 177 */   NON_INVERTIBLE_TRANSFORM("non-invertible affine transform collapses some lines into single points"),
/* 178 */   NON_POSITIVE_MICROSPHERE_ELEMENTS("number of microsphere elements must be positive, but got {0}"),
/* 179 */   NON_POSITIVE_POLYNOMIAL_DEGREE("polynomial degree must be positive: degree={0}"),
/* 180 */   NON_REAL_FINITE_ABSCISSA("all abscissae must be finite real numbers, but {0}-th is {1}"),
/* 181 */   NON_REAL_FINITE_ORDINATE("all ordinatae must be finite real numbers, but {0}-th is {1}"),
/* 182 */   NON_REAL_FINITE_WEIGHT("all weights must be finite real numbers, but {0}-th is {1}"),
/* 183 */   NON_SQUARE_MATRIX("non square ({0}x{1}) matrix"),
/* 184 */   NORMALIZE_INFINITE("Cannot normalize to an infinite value"),
/* 185 */   NORMALIZE_NAN("Cannot normalize to NaN"),
/* 186 */   NOT_ADDITION_COMPATIBLE_MATRICES("{0}x{1} and {2}x{3} matrices are not addition compatible"),
/* 187 */   NOT_DECREASING_NUMBER_OF_POINTS("points {0} and {1} are not decreasing ({2} < {3})"),
/* 188 */   NOT_DECREASING_SEQUENCE("points {3} and {2} are not decreasing ({1} < {0})"),
/* 189 */   NOT_ENOUGH_DATA_FOR_NUMBER_OF_PREDICTORS("not enough data ({0} rows) for this many predictors ({1} predictors)"),
/* 190 */   NOT_ENOUGH_POINTS_IN_SPLINE_PARTITION("spline partition must have at least {0} points, got {1}"),
/* 191 */   NOT_INCREASING_NUMBER_OF_POINTS("points {0} and {1} are not increasing ({2} > {3})"),
/* 192 */   NOT_INCREASING_SEQUENCE("points {3} and {2} are not increasing ({1} > {0})"),
/* 193 */   NOT_MULTIPLICATION_COMPATIBLE_MATRICES("{0}x{1} and {2}x{3} matrices are not multiplication compatible"),
/* 194 */   ALPHA("alpha"),
/* 195 */   BETA("beta"),
/* 196 */   NOT_POSITIVE_DEFINITE_MATRIX("not positive definite matrix"),
/* 197 */   NON_POSITIVE_DEFINITE_MATRIX("not positive definite matrix: diagonal element at ({1},{1}) is smaller than {2} ({0})"),
/* 198 */   NON_POSITIVE_DEFINITE_OPERATOR("non positive definite linear operator"),
/* 199 */   NON_SELF_ADJOINT_OPERATOR("non self-adjoint linear operator"),
/* 200 */   NON_SQUARE_OPERATOR("non square ({0}x{1}) linear operator"),
/* 201 */   DEGREES_OF_FREEDOM("degrees of freedom ({0})"),
/* 202 */   NOT_POSITIVE_DEGREES_OF_FREEDOM("degrees of freedom must be positive ({0})"),
/* 203 */   NOT_POSITIVE_ELEMENT_AT_INDEX("element {0} is not positive: {1}"),
/* 204 */   NOT_POSITIVE_EXPONENT("invalid exponent {0} (must be positive)"),
/* 205 */   EXPONENT("exponent ({0})"),
/* 206 */   NOT_POSITIVE_LENGTH("length must be positive ({0})"),
/* 207 */   LENGTH("length ({0})"),
/* 208 */   NOT_POSITIVE_MEAN("mean must be positive ({0})"),
/* 209 */   MEAN("mean ({0})"),
/* 210 */   NOT_POSITIVE_NUMBER_OF_SAMPLES("number of sample is not positive: {0}"),
/* 211 */   NUMBER_OF_SAMPLES("number of samples ({0})"),
/* 212 */   NOT_POSITIVE_PERMUTATION("permutation k ({0}) must be positive"),
/* 213 */   PERMUTATION_SIZE("permutation size ({0}"),
/* 214 */   NOT_POSITIVE_POISSON_MEAN("the Poisson mean must be positive ({0})"),
/* 215 */   NOT_POSITIVE_POPULATION_SIZE("population size must be positive ({0})"),
/* 216 */   POPULATION_SIZE("population size ({0})"),
/* 217 */   NOT_POSITIVE_ROW_DIMENSION("invalid row dimension: {0} (must be positive)"),
/* 218 */   NOT_POSITIVE_SAMPLE_SIZE("sample size must be positive ({0})"),
/* 219 */   NOT_POSITIVE_SCALE("scale must be positive ({0})"),
/* 220 */   SCALE("scale ({0})"),
/* 221 */   NOT_POSITIVE_SHAPE("shape must be positive ({0})"),
/* 222 */   SHAPE("shape ({0})"),
/* 223 */   NOT_POSITIVE_STANDARD_DEVIATION("standard deviation must be positive ({0})"),
/* 224 */   STANDARD_DEVIATION("standard deviation ({0})"),
/* 225 */   NOT_POSITIVE_UPPER_BOUND("upper bound must be positive ({0})"),
/* 226 */   NOT_POSITIVE_WINDOW_SIZE("window size must be positive ({0})"),
/* 227 */   NOT_POWER_OF_TWO("{0} is not a power of 2"),
/* 228 */   NOT_POWER_OF_TWO_CONSIDER_PADDING("{0} is not a power of 2, consider padding for fix"),
/* 229 */   NOT_POWER_OF_TWO_PLUS_ONE("{0} is not a power of 2 plus one"),
/* 230 */   NOT_STRICTLY_DECREASING_NUMBER_OF_POINTS("points {0} and {1} are not strictly decreasing ({2} <= {3})"),
/* 231 */   NOT_STRICTLY_DECREASING_SEQUENCE("points {3} and {2} are not strictly decreasing ({1} <= {0})"),
/* 232 */   NOT_STRICTLY_INCREASING_KNOT_VALUES("knot values must be strictly increasing"),
/* 233 */   NOT_STRICTLY_INCREASING_NUMBER_OF_POINTS("points {0} and {1} are not strictly increasing ({2} >= {3})"),
/* 234 */   NOT_STRICTLY_INCREASING_SEQUENCE("points {3} and {2} are not strictly increasing ({1} >= {0})"),
/* 235 */   NOT_SUBTRACTION_COMPATIBLE_MATRICES("{0}x{1} and {2}x{3} matrices are not subtraction compatible"),
/* 236 */   NOT_SUPPORTED_IN_DIMENSION_N("method not supported in dimension {0}"),
/* 237 */   NOT_SYMMETRIC_MATRIX("not symmetric matrix"),
/* 238 */   NON_SYMMETRIC_MATRIX("non symmetric matrix: the difference between entries at ({0},{1}) and ({1},{0}) is larger than {2}"),
/* 239 */   NO_BIN_SELECTED("no bin selected"),
/* 240 */   NO_CONVERGENCE_WITH_ANY_START_POINT("none of the {0} start points lead to convergence"),
/* 241 */   NO_DATA("no data"),
/* 242 */   NO_DEGREES_OF_FREEDOM("no degrees of freedom ({0} measurements, {1} parameters)"),
/* 243 */   NO_DENSITY_FOR_THIS_DISTRIBUTION("This distribution does not have a density function implemented"),
/* 244 */   NO_FEASIBLE_SOLUTION("no feasible solution"),
/* 245 */   NO_OPTIMUM_COMPUTED_YET("no optimum computed yet"),
/* 246 */   NO_REGRESSORS("Regression model must include at least one regressor"),
/* 247 */   NO_RESULT_AVAILABLE("no result available"),
/* 248 */   NO_SUCH_MATRIX_ENTRY("no entry at indices ({0}, {1}) in a {2}x{3} matrix"),
/* 249 */   NAN_NOT_ALLOWED("NaN is not allowed"),
/* 250 */   NULL_NOT_ALLOWED("null is not allowed"),
/* 251 */   ARRAY_ZERO_LENGTH_OR_NULL_NOT_ALLOWED("a null or zero length array not allowed"),
/* 252 */   COVARIANCE_MATRIX("covariance matrix"),
/* 253 */   DENOMINATOR("denominator"),
/* 254 */   DENOMINATOR_FORMAT("denominator format"),
/* 255 */   FRACTION("fraction"),
/* 256 */   FUNCTION("function"),
/* 257 */   IMAGINARY_FORMAT("imaginary format"),
/* 258 */   INPUT_ARRAY("input array"),
/* 259 */   NUMERATOR("numerator"),
/* 260 */   NUMERATOR_FORMAT("numerator format"),
/* 261 */   OBJECT_TRANSFORMATION("conversion exception in transformation"),
/* 262 */   REAL_FORMAT("real format"),
/* 263 */   WHOLE_FORMAT("whole format"),
/* 264 */   NUMBER_TOO_LARGE("{0} is larger than the maximum ({1})"),
/* 265 */   NUMBER_TOO_SMALL("{0} is smaller than the minimum ({1})"),
/* 266 */   NUMBER_TOO_LARGE_BOUND_EXCLUDED("{0} is larger than, or equal to, the maximum ({1})"),
/* 267 */   NUMBER_TOO_SMALL_BOUND_EXCLUDED("{0} is smaller than, or equal to, the minimum ({1})"),
/* 268 */   NUMBER_OF_SUCCESS_LARGER_THAN_POPULATION_SIZE("number of successes ({0}) must be less than or equal to population size ({1})"),
/* 269 */   NUMERATOR_OVERFLOW_AFTER_MULTIPLY("overflow, numerator too large after multiply: {0}"),
/* 270 */   N_POINTS_GAUSS_LEGENDRE_INTEGRATOR_NOT_SUPPORTED("{0} points Legendre-Gauss integrator not supported, number of points must be in the {1}-{2} range"),
/* 271 */   OBSERVED_COUNTS_ALL_ZERO("observed counts are all 0 in observed array {0}"),
/* 272 */   OBSERVED_COUNTS_BOTTH_ZERO_FOR_ENTRY("observed counts are both zero for entry {0}"),
/* 273 */   BOBYQA_BOUND_DIFFERENCE_CONDITION("the difference between the upper and lower bound must be larger than twice the initial trust region radius ({0})"),
/* 274 */   OUT_OF_BOUNDS_QUANTILE_VALUE("out of bounds quantile value: {0}, must be in (0, 100]"),
/* 275 */   OUT_OF_BOUND_SIGNIFICANCE_LEVEL("out of bounds significance level {0}, must be between {1} and {2}"),
/* 276 */   SIGNIFICANCE_LEVEL("significance level ({0})"),
/* 277 */   OUT_OF_ORDER_ABSCISSA_ARRAY("the abscissae array must be sorted in a strictly increasing order, but the {0}-th element is {1} whereas {2}-th is {3}"),
/* 278 */   OUT_OF_RANGE_ROOT_OF_UNITY_INDEX("out of range root of unity index {0} (must be in [{1};{2}])"),
/* 279 */   OUT_OF_RANGE("out of range"),
/* 280 */   OUT_OF_RANGE_SIMPLE("{0} out of [{1}, {2}] range"),
/* 281 */   OUT_OF_RANGE_LEFT("{0} out of ({1}, {2}] range"),
/* 282 */   OUT_OF_RANGE_RIGHT("{0} out of [{1}, {2}) range"),
/* 283 */   OUTLINE_BOUNDARY_LOOP_OPEN("an outline boundary loop is open"),
/* 284 */   OVERFLOW("overflow"),
/* 285 */   OVERFLOW_IN_FRACTION("overflow in fraction {0}/{1}, cannot negate"),
/* 286 */   OVERFLOW_IN_ADDITION("overflow in addition: {0} + {1}"),
/* 287 */   OVERFLOW_IN_SUBTRACTION("overflow in subtraction: {0} - {1}"),
/* 288 */   PERCENTILE_IMPLEMENTATION_CANNOT_ACCESS_METHOD("cannot access {0} method in percentile implementation {1}"),
/* 289 */   PERCENTILE_IMPLEMENTATION_UNSUPPORTED_METHOD("percentile implementation {0} does not support {1}"),
/* 290 */   PERMUTATION_EXCEEDS_N("permutation size ({0}) exceeds permuation domain ({1})"),
/* 291 */   POLYNOMIAL("polynomial"),
/* 292 */   POLYNOMIAL_INTERPOLANTS_MISMATCH_SEGMENTS("number of polynomial interpolants must match the number of segments ({0} != {1} - 1)"),
/* 293 */   POPULATION_LIMIT_NOT_POSITIVE("population limit has to be positive"),
/* 294 */   POWER_NEGATIVE_PARAMETERS("cannot raise an integral value to a negative power ({0}^{1})"),
/* 295 */   PROPAGATION_DIRECTION_MISMATCH("propagation direction mismatch"),
/* 296 */   RANDOMKEY_MUTATION_WRONG_CLASS("RandomKeyMutation works only with RandomKeys, not {0}"),
/* 297 */   ROOTS_OF_UNITY_NOT_COMPUTED_YET("roots of unity have not been computed yet"),
/* 298 */   ROTATION_MATRIX_DIMENSIONS("a {0}x{1} matrix cannot be a rotation matrix"),
/* 299 */   ROW_INDEX_OUT_OF_RANGE("row index {0} out of allowed range [{1}, {2}]"),
/* 300 */   ROW_INDEX("row index ({0})"),
/* 301 */   SAME_SIGN_AT_ENDPOINTS("function values at endpoints do not have different signs, endpoints: [{0}, {1}], values: [{2}, {3}]"),
/* 302 */   SAMPLE_SIZE_EXCEEDS_COLLECTION_SIZE("sample size ({0}) exceeds collection size ({1})"),
/* 303 */   SAMPLE_SIZE_LARGER_THAN_POPULATION_SIZE("sample size ({0}) must be less than or equal to population size ({1})"),
/* 304 */   SIMPLEX_NEED_ONE_POINT("simplex must contain at least one point"),
/* 305 */   SIMPLE_MESSAGE("{0}"),
/* 306 */   SINGULAR_MATRIX("matrix is singular"),
/* 307 */   SINGULAR_OPERATOR("operator is singular"),
/* 308 */   SUBARRAY_ENDS_AFTER_ARRAY_END("subarray ends after array end"),
/* 309 */   TOO_LARGE_CUTOFF_SINGULAR_VALUE("cutoff singular value is {0}, should be at most {1}"),
/* 310 */   TOO_LARGE_TOURNAMENT_ARITY("tournament arity ({0}) cannot be bigger than population size ({1})"),
/* 311 */   TOO_MANY_ELEMENTS_TO_DISCARD_FROM_ARRAY("cannot discard {0} elements from a {1} elements array"),
/* 312 */   TOO_MANY_REGRESSORS("too many regressors ({0}) specified, only {1} in the model"),
/* 313 */   TOO_SMALL_COST_RELATIVE_TOLERANCE("cost relative tolerance is too small ({0}), no further reduction in the sum of squares is possible"),
/* 314 */   TOO_SMALL_INTEGRATION_INTERVAL("too small integration interval: length = {0}"),
/* 315 */   TOO_SMALL_ORTHOGONALITY_TOLERANCE("orthogonality tolerance is too small ({0}), solution is orthogonal to the jacobian"),
/* 316 */   TOO_SMALL_PARAMETERS_RELATIVE_TOLERANCE("parameters relative tolerance is too small ({0}), no further improvement in the approximate solution is possible"),
/* 317 */   TRUST_REGION_STEP_FAILED("trust region step has failed to reduce Q"),
/* 318 */   TWO_OR_MORE_CATEGORIES_REQUIRED("two or more categories required, got {0}"),
/* 319 */   TWO_OR_MORE_VALUES_IN_CATEGORY_REQUIRED("two or more values required in each category, one has {0}"),
/* 320 */   UNABLE_TO_BRACKET_OPTIMUM_IN_LINE_SEARCH("unable to bracket optimum in line search"),
/* 321 */   UNABLE_TO_COMPUTE_COVARIANCE_SINGULAR_PROBLEM("unable to compute covariances: singular problem"),
/* 322 */   UNABLE_TO_FIRST_GUESS_HARMONIC_COEFFICIENTS("unable to first guess the harmonic coefficients"),
/* 323 */   UNABLE_TO_ORTHOGONOLIZE_MATRIX("unable to orthogonalize matrix in {0} iterations"),
/* 324 */   UNABLE_TO_PERFORM_QR_DECOMPOSITION_ON_JACOBIAN("unable to perform Q.R decomposition on the {0}x{1} jacobian matrix"),
/* 325 */   UNABLE_TO_SOLVE_SINGULAR_PROBLEM("unable to solve: singular problem"),
/* 326 */   UNBOUNDED_SOLUTION("unbounded solution"),
/* 327 */   UNKNOWN_MODE("unknown mode {0}, known modes: {1} ({2}), {3} ({4}), {5} ({6}), {7} ({8}), {9} ({10}) and {11} ({12})"),
/* 328 */   UNKNOWN_PARAMETER("unknown parameter {0}"),
/* 329 */   UNMATCHED_ODE_IN_EXPANDED_SET("ode does not match the main ode set in the extended set"),
/* 330 */   CANNOT_PARSE_AS_TYPE("string \"{0}\" unparseable (from position {1}) as an object of type {2}"),
/* 331 */   CANNOT_PARSE("string \"{0}\" unparseable (from position {1})"),
/* 332 */   UNPARSEABLE_3D_VECTOR("unparseable 3D vector: \"{0}\""),
/* 333 */   UNPARSEABLE_COMPLEX_NUMBER("unparseable complex number: \"{0}\""),
/* 334 */   UNPARSEABLE_REAL_VECTOR("unparseable real vector: \"{0}\""),
/* 335 */   UNSUPPORTED_EXPANSION_MODE("unsupported expansion mode {0}, supported modes are {1} ({2}) and {3} ({4})"),
/* 336 */   UNSUPPORTED_OPERATION("unsupported operation"),
/* 337 */   ARITHMETIC_EXCEPTION("arithmetic exception"),
/* 338 */   ILLEGAL_STATE("illegal state"),
/* 339 */   USER_EXCEPTION("exception generated in user code"),
/* 340 */   URL_CONTAINS_NO_DATA("URL {0} contains no data"),
/* 341 */   VALUES_ADDED_BEFORE_CONFIGURING_STATISTIC("{0} values have been added before statistic is configured"),
/* 342 */   VECTOR_LENGTH_MISMATCH("vector length mismatch: got {0} but expected {1}"),
/* 343 */   VECTOR_MUST_HAVE_AT_LEAST_ONE_ELEMENT("vector must have at least one element"),
/* 344 */   WEIGHT_AT_LEAST_ONE_NON_ZERO("weigth array must contain at least one non-zero value"),
/* 345 */   WRONG_BLOCK_LENGTH("wrong array shape (block length = {0}, expected {1})"),
/* 346 */   WRONG_NUMBER_OF_POINTS("{0} points are required, got only {1}"),
/* 347 */   NUMBER_OF_POINTS("number of points ({0})"),
/* 348 */   ZERO_DENOMINATOR("denominator must be different from 0"),
/* 349 */   ZERO_DENOMINATOR_IN_FRACTION("zero denominator in fraction {0}/{1}"),
/* 350 */   ZERO_FRACTION_TO_DIVIDE_BY("the fraction to divide by must not be zero: {0}/{1}"),
/* 351 */   ZERO_NORM("zero norm"),
/* 352 */   ZERO_NORM_FOR_ROTATION_AXIS("zero norm for rotation axis"),
/* 353 */   ZERO_NORM_FOR_ROTATION_DEFINING_VECTOR("zero norm for rotation defining vector"),
/* 354 */   ZERO_NOT_ALLOWED("zero not allowed here");
/*     */   
/*     */   private final String sourceFormat;
/*     */   
/*     */   LocalizedFormats(String sourceFormat) {
/* 368 */     this.sourceFormat = sourceFormat;
/*     */   }
/*     */   
/*     */   public String getSourceString() {
/* 373 */     return this.sourceFormat;
/*     */   }
/*     */   
/*     */   public String getLocalizedString(Locale locale) {
/*     */     try {
/* 379 */       String path = LocalizedFormats.class.getName().replaceAll("\\.", "/");
/* 380 */       ResourceBundle bundle = ResourceBundle.getBundle("assets/" + path, locale);
/* 382 */       if (bundle.getLocale().getLanguage().equals(locale.getLanguage()))
/* 384 */         return bundle.getString(toString()); 
/* 387 */     } catch (MissingResourceException mre) {}
/* 393 */     return this.sourceFormat;
/*     */   }
/*     */ }


/* Location:              D:\#source-code\TheFlightSims\TFSLibrary\World2Xplane\World2XPlane.jar!\org\apache\commons\math3\exceptio\\util\LocalizedFormats.class
 * Java compiler version: 5 (49.0)
 * JD-Core Version:       1.1.3
 */